# === A config file for auto-fill lyd option === #
# login
[login]
enable = false # do auto-fill login option

  [login.cookie_path]
  # the path is used if the url contains the key
  # no cookie will be used if all keys are not found
  # cookie will not be used if the path is empty
  # priority from top to bottom
  z = ''
  bilibili = ''

# format
[format]
enable = false
# 0: best quality, 1: quality-efficent balance
prefered_format = 0

# subtitle
[subtitle]
enable = false # do auto-fill subtitle option
do_write_subtitle = true # do write subtitle if any subtitle is found
sub_lang = ['en'] # prefered subtitle language, priority from left to right
embed = true
burn = true

# download
[download]
enable = false # do auto-fill download option
output_dir = ''
