# === A config file for auto-fill lyd option === #
# login
[login]
enable = false # do auto-fill login option

  [login.cookie_path]
  # the path is used if the url contains the key
  # no cookie will be used if all keys are not found
  # cookie will not be used if the path is empty
  # priority from top to bottom
  bilibili = ''

# format
[format]
enable = false
# 0: best quality, 1: best quality lowest size 2: quality-efficent balance
prefered_format = 1

# subtitle
[subtitle]
  [subtitle.do_write_subtitle]
  enable = false # do auto-fill subtitle option
  val = false # do write subtitle if any subtitle is found

  [subtitle.sub_lang]
  enable = false
  val = [] # code of prefered subtitle language, priority from left to right

  [subtitle.write_mode]
  enable = false
  embed = true
  burn = true

# download
[download]
  [download.output_dir]
  enable = false # do auto-fill download option
  val = '' # path
