# === A config file for auto-fill lyd option === #
# login
[login]
enable = false # do auto-fill login option
cookie_path = '' # path to cookie file

# media
[media]
enable = false
# 0: video, 1: audio
val = 0

# format option
[format_option]
enable = false
HRLS = false # high resolution lowest size
WIN = true # make the video play in window

# subtitle
[subtitle]
  [subtitle.do_write_subtitle]
  enable = false # do auto-fill subtitle option
  val = false # do write subtitle if any subtitle is found

  [subtitle.sub_lang]
  enable = false
  val = [] # code of prefered subtitle language, priority from left to right

  [subtitle.write_mode]
  enable = false
  embed = true
  burn = true

# download
[download]
  [download.output_dir]
  enable = false # do auto-fill download option
  val = '' # path
